# SPDX-License-Identifier: PMPL-1.0-or-later
# Svalinn Compose for LCB Website Production
# Requires: Svalinn gateway, Cerro Torre manifests, Vörðr runtime
#
# This configuration uses the verified container stack:
# - Svalinn validates all requests against verified-container-spec
# - Cerro Torre .ctp manifests provide cryptographic provenance
# - Vörðr executes containers with reversible state journal
#
# Status: TEMPLATE - requires component repos to be functional

version: '3.8'

x-svalinn-policy: &default-policy
  verification:
    require_manifest: true
    require_attestation: true
    require_signature: true
  security:
    selinux_enforcing: true
    seccomp_profile: runtime/default
    capabilities_drop:
      - ALL
    capabilities_add:
      - NET_BIND_SERVICE
      - CHOWN
      - SETGID
      - SETUID
  consent:
    enforce_aibdp: true
    aibdp_policy_url: "/.well-known/aibdp.json"
    reject_non_consenting: true

services:
  wordpress:
    # This references the Cerro Torre manifest output
    # After running: ct pack infra/wordpress.ctp
    image: lcb-wordpress:6.9.0
    container_name: lcb-wordpress-prod
    ports:
      - "8080:8080"
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD}
      WORDPRESS_DB_NAME: wordpress
      PHP_AEGIS_ENABLED: 1
      CONSENT_HTTP_ENABLED: 1
    volumes:
      - wordpress_data:/var/www/html
      - wordpress_logs:/var/www/html/wp-content/logs
    depends_on:
      - db
    restart: unless-stopped
    labels:
      - "com.hyperpolymath.stack=production"
      - "com.hyperpolymath.component=wordpress"
      - "com.hyperpolymath.manifest=infra/wordpress.ctp"
      - "com.hyperpolymath.verified=true"
    networks:
      - lcb-network
    # Svalinn-specific policy extensions
    x-svalinn:
      <<: *default-policy
      attestation:
        require:
          - source-signature
          - reproducible-build
          - sbom-complete
        recommend:
          - security-audit
      provenance:
        sbom_path: sbom/spdx/lcb-wordpress.sbom.spdx.json
        provenance_log: in_toto/lcb-wordpress.provenance.jsonl
      oauth2:
        required: true
        scopes:
          - wordpress:read
          - wordpress:write
        issuer: ${OAUTH2_ISSUER}
      rate_limit:
        requests_per_hour: 1000
        burst: 50

  db:
    # Future: Replace with Cerro Torre manifest for hardened MariaDB
    image: mariadb:11.2
    container_name: lcb-mariadb-prod
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: ${WORDPRESS_DB_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
      - ./services/mariadb/my.cnf:/etc/mysql/conf.d/custom.cnf:ro
    restart: unless-stopped
    labels:
      - "com.hyperpolymath.stack=production"
      - "com.hyperpolymath.component=database"
    networks:
      - lcb-network
    x-svalinn:
      <<: *default-policy
      # DB doesn't need attestation but should be isolated
      verification:
        require_manifest: false
        require_attestation: false
      network:
        internal: true
        expose_only_to:
          - wordpress

  varnish:
    # Future: Cerro Torre manifest for Varnish with consent-aware VCL
    image: varnish:7.4
    container_name: lcb-varnish-prod
    ports:
      - "80:80"
      - "443:443"
    environment:
      VARNISH_SIZE: 512M
      CONSENT_HTTP_ENABLED: 1
    volumes:
      - ./services/varnish/production.vcl:/etc/varnish/default.vcl:ro
      - ./services/varnish/consent-check.vcl:/etc/varnish/consent-check.vcl:ro
      - varnish_cache:/var/lib/varnish
    depends_on:
      - wordpress
    restart: unless-stopped
    labels:
      - "com.hyperpolymath.stack=production"
      - "com.hyperpolymath.component=cache"
    networks:
      - lcb-network
    command: ["-a", "http=:80,HTTP", "-a", "https=:443,PROXY", "-p", "feature=+http2", "-F", "-f", "/etc/varnish/default.vcl"]
    x-svalinn:
      <<: *default-policy
      verification:
        require_manifest: false
      consent:
        enforce_aibdp: true
        aibdp_policy_url: "/.well-known/aibdp.json"
        reject_non_consenting: true
        return_430: true

volumes:
  wordpress_data:
    driver: local
  wordpress_logs:
    driver: local
  db_data:
    driver: local
  varnish_cache:
    driver: local

networks:
  lcb-network:
    driver: bridge
    labels:
      - "com.hyperpolymath.environment=production"
      - "com.hyperpolymath.verified-stack=true"

# Svalinn Gateway Configuration
# This section is consumed by svalinn-compose CLI
x-svalinn-gateway:
  version: "1.0"
  runtime: vordr
  gateway:
    address: 0.0.0.0
    port: 8000
    tls:
      enabled: true
      cert: /etc/svalinn/tls/cert.pem
      key: /etc/svalinn/tls/key.pem
  verification:
    cerro_torre_path: /opt/cerro-torre/bin/ct
    manifest_cache: /var/cache/svalinn/manifests
    attestation_store: /var/lib/svalinn/attestations
  vordr:
    endpoint: http://localhost:8080/rpc
    auth_token: ${VORDR_AUTH_TOKEN}
  logging:
    level: info
    format: json
    destinations:
      - stdout
      - file:///var/log/svalinn/gateway.log
      - feedback-o-tron:///api/v1/submit
